# yaml-language-server: $schema=https://json.schemastore.org/pubspec.json
name: news
description: Flutter app for KweeksNews site

version: 2.0.0+2
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dismissible_page: ^0.7.2
  drift: ^2.1.0
  equatable: ^2.0.3
  firebase_analytics: ^10.0.3
  firebase_core: ^2.1.1
  flex_color_scheme: ^6.0.1
  flutter:
    sdk: flutter
  flutter_html: ^2.2.1
  flutter_inappwebview: ^5.4.3+7
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  flutter_speed_dial: ^6.0.0
  flutter_web_plugins:
    sdk: flutter
  fluttertoast: ^8.1.1
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^6.0.0
  graphql: ^5.1.1
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  html_unescape: ^2.0.0
  infinite_scroll_pagination: ^3.2.0
  injectable: ^2.0.0
  intl: ^0.17.0
  meta: ^1.7.0
  nil: ^1.1.1
  package_info_plus: ^3.0.1
  path: ^1.8.1
  path_provider: ^2.0.10
  path_to_regexp: ^0.4.0
  photo_view: ^0.14.0
  share_plus: ^6.1.0
  shimmer: ^2.0.0
  sqlite3_flutter_libs: ^0.5.7
  timeago: ^3.2.2
  timeago_flutter: ^1.1.0
  url_launcher: ^6.1.2
  youtube_player_flutter: ^8.1.0

dev_dependencies:
  build_runner: null
  drift_dev: ^2.1.0
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.0+1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  injectable_generator: ^2.0.0
  mockito: ^5.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/error.png
    - assets/img/no_data.png
    - assets/img/placeholder.png
    - assets/img/search.png
    - assets/img/dark/logo.png
    - assets/img/light/logo.png

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri/Amiri-Bold.ttf
        - asset: assets/fonts/Amiri/Amiri-BoldItalic.ttf
        - asset: assets/fonts/Amiri/Amiri-Italic.ttf
        - asset: assets/fonts/Amiri/Amiri-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat/Montserrat-LightItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ThinItalic.ttf

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Light.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand/Quicksand-SemiBold.ttf

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: assets/l10n
  output_dir: lib/presentation/l10n/generated

flutter_icons:
  android: true
  ios: true
  image_path_android: assets/img/icon_launcher_android_legacy.png
  image_path_ios: assets/img/icon_launcher_ios.png
  adaptive_icon_background: "#FF000000"
  adaptive_icon_foreground: assets/img/icon_launcher_android_adaptive.png
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image: assets/img/light/logo.png
  image_dark: assets/img/dark/logo.png
